# OpenBao HA Cluster — ${node_count} nodes with Raft storage
# Auto-generated by Terraform. Do not edit manually.
#
# Usage:
#   docker compose -f docker-compose-ha.yml up -d
#   # Initialize the first node:
#   docker exec ${cluster_name}-0 bao operator init -key-shares=1 -key-threshold=1
#   # Unseal and join remaining nodes

version: "3.8"

networks:
  openbao-ha:
    driver: bridge

services:
%{ for i in range(node_count) ~}
  ${cluster_name}-${i}:
    image: ${openbao_image}
    container_name: ${cluster_name}-${i}
    hostname: ${cluster_name}-${i}
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ports:
%{ if i == 0 ~}
      - "8200:8200"
      - "8201:8201"
%{ endif ~}
    volumes:
      - ./node-${i}/config.hcl:/etc/openbao/config.hcl:ro
      - openbao-data-${i}:/opt/openbao/data
    environment:
      BAO_LOCAL_CONFIG: ""
      BAO_API_ADDR: "http://${cluster_name}-${i}:8200"
      BAO_CLUSTER_ADDR: "http://${cluster_name}-${i}:8201"
    command: ["server"]
    networks:
      - openbao-ha
    healthcheck:
      test: ["CMD", "bao", "status", "-format=json"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

%{ endfor ~}

volumes:
%{ for i in range(node_count) ~}
  openbao-data-${i}:
%{ endfor ~}
