# OpenBao Server Configuration — ${node_id}
# Auto-generated by Terraform. Do not edit manually.

cluster_name = "${cluster_name}"

ui = ${enable_ui}

log_level = "${log_level}"

%{ if tls_enabled }
listener "tcp" {
  address       = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_cert_file = "${tls_cert_file}"
  tls_key_file  = "${tls_key_file}"
  tls_min_version = "tls12"
}
%{ else }
listener "tcp" {
  address       = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_disable   = true
}
%{ endif }

# Integrated Raft storage for HA
storage "raft" {
  path    = "/opt/openbao/data"
  node_id = "${node_id}"

%{ for peer in cluster_nodes ~}
%{ if peer.id != node_id ~}
  retry_join {
    leader_api_addr = "http://${peer.addr}"
  }
%{ endif ~}
%{ endfor ~}
}

api_addr     = "${api_addr}"
cluster_addr = "${cluster_addr}"

# Telemetry for Prometheus scraping
telemetry {
  prometheus_retention_time = "30s"
  disable_hostname         = true
}

%{ if auto_unseal_enabled }
# Transit auto-unseal via external Vault/OpenBao
seal "transit" {
  address     = "${auto_unseal_addr}"
  token       = "${auto_unseal_token}"
  key_name    = "${auto_unseal_key_name}"
  mount_path  = "transit/"
}
%{ endif }

# Memory locking — prevents sensitive data from being swapped to disk
disable_mlock = false

# Max request duration
max_request_duration = "90s"
