# LoadBalancer — Docker Desktop tự map ra localhost
# Truy cập app tại: http://localhost:8000
apiVersion: v1
kind: Service
metadata:
  name: tnt-engine
  namespace: tnt-engine
  labels:
    app: tnt-engine
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: tnt-engine
